# Generated by Django 4.2.10 on 2026-09-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="template",
            field=models.CharField(
                choices=[
                    ("classic", "Classique"),
                    ("modern", "Moderne"),
                    ("creative", "Créatif"),
                ],
                default="classic",
                max_length=20,
            ),
        ),
    ]
