# Generated by Django 4.2.10 on 2026-09-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_generator", "0003_alter_cv_options_cv_title_alter_cv_full_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="cv",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="cv",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="cv",
        ),
        migrations.AlterModelOptions(
            name="cv",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.RemoveField(
            model_name="cv",
            name="title",
        ),
        migrations.AlterField(
            model_name="cv",
            name="full_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="cv",
            name="template",
            field=models.CharField(default="modern", max_length=50),
        ),
        migrations.DeleteModel(
            name="Education",
        ),
        migrations.DeleteModel(
            name="Experience",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
