# Generated by Django 4.2.10 on 2026-09-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_generator", "0004_remove_experience_cv_remove_payment_cv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="cv_photos/"),
        ),
    ]
